using System;
using System.Collections.Generic;

namespace ListdbTc.DAL.Models
{
    public partial class MttoUnidades
    {
        public string IdUnidad { get; set; }
        public int? TotalLlantas { get; set; }
        public int? TipoUnidad { get; set; }
        public int? IdTipoMotor { get; set; }
        public int IdMarcaUnidad { get; set; }
        public int IdTipoUnidad { get; set; }
        public int KmsAcumulados { get; set; }
        public int? RFV { get; set; }
        public int? IdCentroCosto { get; set; }
        public int? LlantasExtras { get; set; }
        public int? NoPermiso { get; set; }
        public int? NoIncisoSeguro { get; set; }
        public int? IdOperador { get; set; }
        public int? KmsServicioUltimo { get; set; }
        public int? KmsServicioSig { get; set; }
        public int IdArea { get; set; }
        public int IdDepto { get; set; }
        public int? KmsInicioCiclo { get; set; }
        public int? SecuenciaInicio { get; set; }
        public int? Idcia { get; set; }
        public decimal? HrsInicioCiclo { get; set; }
        public int? NoCilindros { get; set; }
        public int? ProvCarroceria { get; set; }
        public int? SecuenciaUlt { get; set; }
        public int? SecuenciaSig { get; set; }
        public int? NoCircula { get; set; }
        public int? DobleNoCircula { get; set; }
        public int? IdTercero { get; set; }
        public int? IdStatus { get; set; }
        public int? StatusComm { get; set; }
        public int? MsgPend { get; set; }
        public int? IdRuta { get; set; }
        public int? IdAreaViaje { get; set; }
        public int? NoViaje { get; set; }
        public int? IdPedido { get; set; }
        public int? IdFlota { get; set; }
        public int? IdOrigen { get; set; }
        public int? IdDestino { get; set; }
        public int? IdRemitente { get; set; }
        public int? IdDestinatario { get; set; }
        public int? IdMacroUlt { get; set; }
        public decimal? CostoTenencia { get; set; }
        public decimal? NoPoliza { get; set; }
        public decimal? PrimaNeta { get; set; }
        public decimal? Recargos { get; set; }
        public decimal? DerPoliza { get; set; }
        public decimal? Iva { get; set; }
        public decimal? CostoUnidad { get; set; }
        public decimal? CostoCarroceria { get; set; }
        public DateTime? UltimaTenencia { get; set; }
        public DateTime? UltimoRefrendo { get; set; }
        public DateTime? UltimoPermiso { get; set; }
        public DateTime? VenceSeguro { get; set; }
        public DateTime? FechaKms { get; set; }
        public DateTime? FechaServicioUltimo { get; set; }
        public DateTime? FechaServicioSig { get; set; }
        public DateTime? FechaAdquisicion { get; set; }
        public DateTime? FechaUltimaRev { get; set; }
        public DateTime? FechaInicioCiclo { get; set; }
        public DateTime? FechaEmision { get; set; }
        public DateTime? FechaDesde { get; set; }
        public DateTime? FechaHasta { get; set; }
        public DateTime? FechaAdqCarr { get; set; }
        public DateTime? FechaEstatus { get; set; }
        public DateTime? FechaBaja { get; set; }
        public DateTime? Posdate { get; set; }
        public DateTime? FRealSalida { get; set; }
        public DateTime? FProgLlegada { get; set; }
        public DateTime? FEntradaPatio { get; set; }
        public DateTime? FMismapos { get; set; }
        public DateTime? Tea { get; set; }
        public decimal? RendimientoEsperado { get; set; }
        public decimal? LtsCombustible { get; set; }
        public decimal? LtsAceite { get; set; }
        public decimal? KmsPorDia { get; set; }
        public decimal? DimAncho { get; set; }
        public decimal? DimLargo { get; set; }
        public decimal? DimAltura { get; set; }
        public decimal? RendimientoAceite { get; set; }
        public decimal? HrsAcumuladas { get; set; }
        public decimal? HrsPorDia { get; set; }
        public decimal? HrsServicioUltimo { get; set; }
        public decimal? HrsServicioSig { get; set; }
        public decimal? Proveedor { get; set; }
        public decimal? PesoUnidades { get; set; }
        public decimal? LtsRelleno { get; set; }
        public decimal? LtsSaldocomb { get; set; }
        public string NoSerie { get; set; }
        public string Modelo { get; set; }
        public string IdCicloPreventivo { get; set; }
        public string Placas { get; set; }
        public string Observaciones { get; set; }
        public string NoEconomico { get; set; }
        public string IdServicioUltimo { get; set; }
        public string IdServicioSig { get; set; }
        public string IdServicioInicio { get; set; }
        public string TarjetaCirculacion { get; set; }
        public string NoFactura { get; set; }
        public string TipoMotor { get; set; }
        public string PotenciaMotor { get; set; }
        public string PulgadasCubicas { get; set; }
        public string NoMotor { get; set; }
        public string Color { get; set; }
        public string NoCarroceria { get; set; }
        public string ObsCarroceria { get; set; }
        public DateTime? FechaVencePlacas { get; set; }
        public string Poliza { get; set; }
        public DateTime? FechaVenceTenencia { get; set; }
        public string StatusUnidad { get; set; }
        public string Viaje { get; set; }
        public DateTime? FechaVenceSeguro { get; set; }
        public string IdThermo { get; set; }
        public DateTime? FechaVenceVerificacion { get; set; }
        public string NoKit { get; set; }
        public string DescMarcamotor { get; set; }
        public string DescProvcarroceria { get; set; }
        public string DescProvunidad { get; set; }
        public string TarjetaLlave { get; set; }
        public string NoTarjetaLlave { get; set; }
        public string Mctnumber { get; set; }
        public string Posicion { get; set; }
        public decimal? Poslat { get; set; }
        public decimal? Poslon { get; set; }
        public string Operador { get; set; }
        public string IdUnidadAs { get; set; }
        public string IdRemolque1 { get; set; }
        public string IdDolly { get; set; }
        public string IdRemolque2 { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string IdDespachador { get; set; }
        public string TipoCombustible { get; set; }
        public string Estado { get; set; }
        public string EstadoAdquisicion { get; set; }
        public string DatosGenerales { get; set; }
        public string TipoMoneda { get; set; }
        public string FormaPago { get; set; }
        public string KmsHrs { get; set; }
        public string HrsAutomaticas { get; set; }
        public string Estatus { get; set; }
        public string TipoProgramacion { get; set; }
        public string EquipoOmnitracs { get; set; }
        public string Tercero { get; set; }
        public string CausaBaja { get; set; }
        public string Tipo { get; set; }
        public string Status { get; set; }
        public string StatusCaja1 { get; set; }
        public string StatusCaja2 { get; set; }
        public string EnPatio { get; set; }
        public string Mismapos { get; set; }
        public DateTime? FStatusUnidad { get; set; }
        public string Subcta { get; set; }
        public string TipomacroUlt { get; set; }
        public int KmsActuales { get; set; }
        public string Ruta { get; set; }
        public int? PesoBruto { get; set; }
        public DateTime? FechaInstalacion { get; set; }
        public int? Kmshrsinicialaparmed { get; set; }
        public int? NoMedidor { get; set; }
        public string TipoMedida { get; set; }
        public int? IdOperador2 { get; set; }
        public decimal HrsActuales { get; set; }
        public string IdIngreso { get; set; }
        public DateTime? FechaIngreso { get; set; }
        public int? KmsHrsActuales { get; set; }
        public DateTime? FechaDisponible { get; set; }
        public int IdPlazadestino { get; set; }
        public int IdTipoOperacion { get; set; }
        public int IdMovimiento { get; set; }
        public string ClasUni { get; set; }
        public string CtaConsumo { get; set; }
        public int IdStatusRem { get; set; }
        public int UltimoIdDestinatario { get; set; }
        public int UltimoIdAreaViaje { get; set; }
        public int UltimoNoViaje { get; set; }
        public int IdEstacion { get; set; }
        public int UltimoIdAreapedido { get; set; }
        public int UltimoIdPedido { get; set; }
        public int OrigenStatus { get; set; }
        public string Cargadovacio { get; set; }
        public int? KmsUltimaRev { get; set; }
        public string IdTransponder { get; set; }
        public string NumSoporte { get; set; }
        public string Vehunitnum { get; set; }
        public int? Nacionalidad { get; set; }
        public int IdLocalidaddestino { get; set; }
        public int IdCircuito { get; set; }
        public int IdCompania { get; set; }
        public int KmsArribo { get; set; }
        public int UltimoIdPedidopk { get; set; }
        public int Alarmasnuevas { get; set; }
        public int Mensajesnuevos { get; set; }
        public string IdLinearem1 { get; set; }
        public string IdLinearem2 { get; set; }
        public int Modulo { get; set; }
        public int IdAsignacion { get; set; }
        public int? IdOperador3 { get; set; }
        public decimal? PorcPagoOp1 { get; set; }
        public decimal? PorcPagoOp2 { get; set; }
        public decimal? PorcPagoOp3 { get; set; }
        public decimal SaldoCombustible { get; set; }
        public string PlacaIzq { get; set; }
        public string PlacaDer { get; set; }
        public string ModeloUnidad { get; set; }
        public string Madre { get; set; }
        public string Hija { get; set; }
        public string Asignado { get; set; }
        public string UnidadAsignado { get; set; }
        public string HijaAsignada { get; set; }
        public DateTime? FechaLogistica { get; set; }
        public decimal? ValorConvenido { get; set; }
        public decimal? DeducibleXrobo { get; set; }
        public decimal? DeducibleXdmateriales { get; set; }
        public decimal Faset { get; set; }
        public int JefeFlota { get; set; }
        public int IdPlazasigdestino { get; set; }
        public string NoOrsan { get; set; }
        public int ValidaCargacomb { get; set; }
        public bool Procesado { get; set; }
        public decimal Disponibilidad { get; set; }
        public string CapacidadAliado { get; set; }
        public string MarcaCapEjeDelantero { get; set; }
        public string MarcaCapEjeTrasero { get; set; }
        public string MarcaModeloTipoTransmision { get; set; }
        public string MarcaSuspension { get; set; }
        public string MedidaLlanta { get; set; }
        public string TipoEjes { get; set; }
        public string TipoSuspension { get; set; }
        public string MarcaAliado { get; set; }
        public int AnoFabricacion { get; set; }
        public int? IdHistogramaSig { get; set; }
        public int? IdHistogramaUltimo { get; set; }
        public DateTime? FechaFinGarantia { get; set; }
        public int? IdAccion { get; set; }
        public int? IdProject { get; set; }
        public int Ccosto { get; set; }
        public int? IdTipoServicioUnidad { get; set; }
        public int IdSector { get; set; }
        public int IdSubflota { get; set; }
        public string EmEmail { get; set; }
        public string CtaMayor { get; set; }
    }
}
