using System;
using System.Collections.Generic;

namespace ListdbTc.DAL.Models
{
    public partial class TraficoCliente
    {
        public int IdCliente { get; set; }
        public int? DiasCredito { get; set; }
        public int? IdGpocliente { get; set; }
        public int IdPlaza { get; set; }
        public int ConsecCobranza { get; set; }
        public int Matriz { get; set; }
        public int AreaCobranza { get; set; }
        public decimal? TiempoCarga { get; set; }
        public decimal? TiempoDescarga { get; set; }
        public decimal? FactorIva { get; set; }
        public decimal? ValorPagoOperador { get; set; }
        public decimal? Latpos { get; set; }
        public decimal? Lonpos { get; set; }
        public decimal MontoManiobras { get; set; }
        public string Nombre { get; set; }
        public string Rfc { get; set; }
        public string Domicilio { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Contacto1 { get; set; }
        public string Contacto2 { get; set; }
        public string CuentaCliente { get; set; }
        public string SubctaCliente { get; set; }
        public string PrNombre { get; set; }
        public string ObservacionesCliente { get; set; }
        public string TipoCliente { get; set; }
        public string TipoCredito { get; set; }
        public int? Prioridad { get; set; }
        public string Lunes { get; set; }
        public string Martes { get; set; }
        public string Omnionline { get; set; }
        public string Miercoles { get; set; }
        public string Jueves { get; set; }
        public string Viernes { get; set; }
        public string Sabado { get; set; }
        public string ControlarPago { get; set; }
        public string TipoPago { get; set; }
        public string Instrucciones { get; set; }
        public decimal FactorKmscobro { get; set; }
        public string NumCliente { get; set; }
        public int IdClienteplanta { get; set; }
        public string SistOrigen { get; set; }
        public int Personafisica { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public decimal MontoCredito { get; set; }
        public decimal MontoAdvertencia { get; set; }
        public string CreditoActivo { get; set; }
        public int? TipoRetencion { get; set; }
        public int? ClienteQuePaga { get; set; }
        public int IdIva { get; set; }
        public int IdRetencion { get; set; }
        public int IdSeguro { get; set; }
        public string AuxiliarCliente { get; set; }
        public int? ClienteSincobro { get; set; }
        public int? Extranjero { get; set; }
        public int? IdDesctosuterm { get; set; }
        public decimal PorcDesctosuterm { get; set; }
        public int? IdDesctofide { get; set; }
        public decimal? PorcDesctofide { get; set; }
        public int IdAddenda { get; set; }
        public string Cp { get; set; }
        public int TipoXml { get; set; }
        public int? IdCobrador { get; set; }
        public string IdIngreso { get; set; }
        public string IdModifico { get; set; }
        public DateTime? FechaIngreso { get; set; }
        public DateTime? FechaModifico { get; set; }
        public int IdClientePerm { get; set; }
        public string Estatus { get; set; }
        public int RepetirRemision { get; set; }
        public int IdCompania { get; set; }
        public string Nra { get; set; }
        public string Ubicacion1 { get; set; }
        public string Ubicacion2 { get; set; }
        public string Ubicacion3 { get; set; }
        public string Comentarios { get; set; }
        public string NumClientext { get; set; }
        public string Nombrext { get; set; }
        public int Asegurado { get; set; }
        public string Dealer { get; set; }
        public int CalculaSeguro { get; set; }
        public int IdEjecutivo { get; set; }
        public string CodigoDinet { get; set; }
        public string Instrucciones1 { get; set; }
        public string Instrucciones2 { get; set; }
        public int AddendaAmece { get; set; }
        public string CteAseguradora { get; set; }
        public string MostrarIeps { get; set; }
        public string Redondeo { get; set; }
        public int CveMarca { get; set; }
        public string OcultaFlete { get; set; }
        public string OcultaFleteHojains { get; set; }
        public int IdClientePemex { get; set; }
        public string ClienteScmt { get; set; }
        public bool Procesado { get; set; }
        public int? IdUsoCfdi { get; set; }
        public int? ResponsableCliente { get; set; }
        public int? IdTipoArmadora { get; set; }
        public int? Cartacobroauto { get; set; }
        public int? EnvioEvidenciasAuto { get; set; }
        public int? ReferenciaCliente { get; set; }
        public int HorasCarga { get; set; }
        public int HorasDescarga { get; set; }
        public bool? FacturaCpSinliq { get; set; }
        public string Contacto3 { get; set; }
        public string Contacto4 { get; set; }
        public string Contacto5 { get; set; }
        public string Contacto6 { get; set; }
        public string Referencia { get; set; }
        public bool ContribuyenteRif { get; set; }
        public bool SectorPrimario { get; set; }
        public bool IntegranteSistemaFinanciero { get; set; }
        public string MostrarBanco { get; set; }
        public decimal MontoAdvertenciaUsd { get; set; }
        public decimal MontoCreditoUsd { get; set; }
        public int BitacoraLibre { get; set; }
        public string PolizaSeguro { get; set; }
        public string UsoGuia { get; set; }
        public decimal? UsoGuiaValor { get; set; }
        public string Ferrie { get; set; }
        public decimal? FerrieValor { get; set; }
        public string Pension { get; set; }
        public decimal? PensionValor { get; set; }
        public string Taxis { get; set; }
        public decimal? TaxisValor { get; set; }
        public string NumTelefonos { get; set; }
        public string RestriccionCirculacion { get; set; }
        public string RestriccionCirculacion1 { get; set; }
        public string RestriccionCirculacion2 { get; set; }
        public string RestriccionCirculacion3 { get; set; }
        public string RestriccionCirculacion4 { get; set; }
        public string HorariosRecepcion { get; set; }
        public string HorariosRecepcion1 { get; set; }
        public string HorariosRecepcion2 { get; set; }
        public string HorariosRecepcion3 { get; set; }
        public string HorariosRecepcion4 { get; set; }
    }
}
