/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InternalTransferTruck : BaseEntity, IEquatable<InternalTransferTruck>
    { 
        /// <summary>
        /// El id del tráctor
        /// </summary>
        /// <value>El id del tráctor</value>
        [Required]
        [DataMember(Name="truck")]
        public int? Truck { get; set; }

        /// <summary>
        /// Origen
        /// </summary>
        /// <value>Origen</value>
        [Required]
        [DataMember(Name="origin")]
        public int? Origin { get; set; }

        /// <summary>
        /// Destino
        /// </summary>
        /// <value>Destino</value>
        [Required]
        [DataMember(Name="destination")]
        public int? Destination { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InternalTransferTruck {\n");
            sb.Append("  Truck: ").Append(Truck).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  Destination: ").Append(Destination).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InternalTransferTruck)obj);
        }

        /// <summary>
        /// Returns true if InternalTransferTruck instances are equal
        /// </summary>
        /// <param name="other">Instance of InternalTransferTruck to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InternalTransferTruck other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Truck == other.Truck ||
                    Truck != null &&
                    Truck.Equals(other.Truck)
                ) && 
                (
                    Origin == other.Origin ||
                    Origin != null &&
                    Origin.Equals(other.Origin)
                ) && 
                (
                    Destination == other.Destination ||
                    Destination != null &&
                    Destination.Equals(other.Destination)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Truck != null)
                    hashCode = hashCode * 59 + Truck.GetHashCode();
                    if (Origin != null)
                    hashCode = hashCode * 59 + Origin.GetHashCode();
                    if (Destination != null)
                    hashCode = hashCode * 59 + Destination.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InternalTransferTruck left, InternalTransferTruck right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InternalTransferTruck left, InternalTransferTruck right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
