/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class LoadPlan : IEquatable<LoadPlan>
    { 
        /// <summary>
        /// El id del tipo de mercado
        /// </summary>
        /// <value>El id del tipo de mercado</value>
        [Required]
        [DataMember(Name="market_type")]
        public int? MarketType { get; set; }

        /// <summary>
        /// El id de este cliente
        /// </summary>
        /// <value>El id de este cliente</value>
        [Required]
        [DataMember(Name="customer")]
        public int? Customer { get; set; }

        /// <summary>
        /// El id de la oficina
        /// </summary>
        /// <value>El id de la oficina</value>
        [Required]
        [DataMember(Name="office")]
        public int? Office { get; set; }

        /// <summary>
        /// Fecha programada
        /// </summary>
        /// <value>Fecha programada</value>
        [Required]
        [DataMember(Name="date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Gets or Sets Vins
        /// </summary>
        [Required]
        [DataMember(Name="vins")]
        public VinsPlan Vins { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LoadPlan {\n");
            sb.Append("  MarketType: ").Append(MarketType).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  Office: ").Append(Office).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Vins: ").Append(Vins).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LoadPlan)obj);
        }

        /// <summary>
        /// Returns true if LoadPlan instances are equal
        /// </summary>
        /// <param name="other">Instance of LoadPlan to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoadPlan other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MarketType == other.MarketType ||
                    MarketType != null &&
                    MarketType.Equals(other.MarketType)
                ) && 
                (
                    Customer == other.Customer ||
                    Customer != null &&
                    Customer.Equals(other.Customer)
                ) && 
                (
                    Office == other.Office ||
                    Office != null &&
                    Office.Equals(other.Office)
                ) && 
                (
                    Date == other.Date ||
                    Date != null &&
                    Date.Equals(other.Date)
                ) && 
                (
                    Vins == other.Vins ||
                    Vins != null &&
                    Vins.Equals(other.Vins)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MarketType != null)
                    hashCode = hashCode * 59 + MarketType.GetHashCode();
                    if (Customer != null)
                    hashCode = hashCode * 59 + Customer.GetHashCode();
                    if (Office != null)
                    hashCode = hashCode * 59 + Office.GetHashCode();
                    if (Date != null)
                    hashCode = hashCode * 59 + Date.GetHashCode();
                    if (Vins != null)
                    hashCode = hashCode * 59 + Vins.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LoadPlan left, LoadPlan right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LoadPlan left, LoadPlan right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
