/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Viajes.Api.Extensions;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OfficePlan : IEquatable<OfficePlan>
    { 
        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="office")]
        public Office Office { get; set; }

        /// <summary>
        /// Gets or Sets TrucksPlan
        /// </summary>
        [DataMember(Name="trucks_plan")]
        public TrucksPlan TrucksPlan { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OfficePlan {\n");
            sb.Append("  Office: ").Append(Office).Append("\n");
            sb.Append("  TrucksPlan: ").Append(TrucksPlan).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OfficePlan)obj);
        }

        /// <summary>
        /// Returns true if OfficePlan instances are equal
        /// </summary>
        /// <param name="other">Instance of OfficePlan to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OfficePlan other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Office == other.Office ||
                    Office != null &&
                    Office.Equals(other.Office)
                ) && 
                (
                    TrucksPlan == other.TrucksPlan ||
                    TrucksPlan != null &&
                    TrucksPlan.Equals(other.TrucksPlan)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Office != null)
                    hashCode = hashCode * 59 + Office.GetHashCode();
                    if (TrucksPlan != null)
                    hashCode = hashCode * 59 + TrucksPlan.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(OfficePlan left, OfficePlan right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OfficePlan left, OfficePlan right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
