/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Tiene la lista de los totales del seguimiento
    /// </summary>
    [DataContract]
    public partial class TrackingNotAvailableDetails : IEquatable<TrackingNotAvailableDetails>
    { 
        /// <summary>
        /// Gets or Sets TypeMarket
        /// </summary>

        [DataMember(Name="typeMarket")]
        public BaseIdAndName TypeMarket { get; set; }

        /// <summary>
        /// Gets or Sets Office
        /// </summary>

        [DataMember(Name="office")]
        public BaseIdAndName Office { get; set; }

        /// <summary>
        /// Gets or Sets Customer
        /// </summary>

        [DataMember(Name="customer")]
        public BaseIdAndName Customer { get; set; }

        /// <summary>
        /// Gets or Sets Operators
        /// </summary>

        [DataMember(Name="operators")]
        public List<TrackingNotAvailableDetail> Operators { get; set; }

        /// <summary>
        /// Gets or Sets Truks
        /// </summary>

        [DataMember(Name="truks")]
        public List<TrackingNotAvailableDetail> Truks { get; set; }

        /// <summary>
        /// Gets or Sets Plan
        /// </summary>

        [DataMember(Name="plan")]
        public List<TrackingNotAvailableDetail> Plan { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TrackingNotAvailableDetails {\n");
            sb.Append("  TypeMarket: ").Append(TypeMarket).Append("\n");
            sb.Append("  Office: ").Append(Office).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  Operators: ").Append(Operators).Append("\n");
            sb.Append("  Truks: ").Append(Truks).Append("\n");
            sb.Append("  Plan: ").Append(Plan).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TrackingNotAvailableDetails)obj);
        }

        /// <summary>
        /// Returns true if TrackingNotAvailableDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of TrackingNotAvailableDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrackingNotAvailableDetails other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TypeMarket == other.TypeMarket ||
                    TypeMarket != null &&
                    TypeMarket.Equals(other.TypeMarket)
                ) && 
                (
                    Office == other.Office ||
                    Office != null &&
                    Office.Equals(other.Office)
                ) && 
                (
                    Customer == other.Customer ||
                    Customer != null &&
                    Customer.Equals(other.Customer)
                ) && 
                (
                    Operators == other.Operators ||
                    Operators != null &&
                    Operators.SequenceEqual(other.Operators)
                ) && 
                (
                    Truks == other.Truks ||
                    Truks != null &&
                    Truks.SequenceEqual(other.Truks)
                ) && 
                (
                    Plan == other.Plan ||
                    Plan != null &&
                    Plan.SequenceEqual(other.Plan)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TypeMarket != null)
                    hashCode = hashCode * 59 + TypeMarket.GetHashCode();
                    if (Office != null)
                    hashCode = hashCode * 59 + Office.GetHashCode();
                    if (Customer != null)
                    hashCode = hashCode * 59 + Customer.GetHashCode();
                    if (Operators != null)
                    hashCode = hashCode * 59 + Operators.GetHashCode();
                    if (Truks != null)
                    hashCode = hashCode * 59 + Truks.GetHashCode();
                    if (Plan != null)
                    hashCode = hashCode * 59 + Plan.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TrackingNotAvailableDetails left, TrackingNotAvailableDetails right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TrackingNotAvailableDetails left, TrackingNotAvailableDetails right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
