/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Travel : IEquatable<Travel>
    { 
        /// <summary>
        /// Gets or Sets Destination
        /// </summary>
        [Required]
        [DataMember(Name="destination")]
        public Location Destination { get; set; }

        /// <summary>
        /// Gets or Sets TravelCost
        /// </summary>
        [Required]
        [DataMember(Name="travel_cost")]
        public TravelCost TravelCost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Travel {\n");
            sb.Append("  Destination: ").Append(Destination).Append("\n");
            sb.Append("  TravelCost: ").Append(TravelCost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Travel)obj);
        }

        /// <summary>
        /// Returns true if Travel instances are equal
        /// </summary>
        /// <param name="other">Instance of Travel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Travel other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Destination == other.Destination ||
                    Destination != null &&
                    Destination.Equals(other.Destination)
                ) && 
                (
                    TravelCost == other.TravelCost ||
                    TravelCost != null &&
                    TravelCost.Equals(other.TravelCost)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Destination != null)
                    hashCode = hashCode * 59 + Destination.GetHashCode();
                    if (TravelCost != null)
                    hashCode = hashCode * 59 + TravelCost.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Travel left, Travel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Travel left, Travel right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
