/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class LoadPlansMetrics : IEquatable<LoadPlansMetrics>
    { 
        /// <summary>
        /// Fecha
        /// </summary>
        /// <value>Fecha</value>
        [Required]

        [DataMember(Name="date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Gets or Sets Trucks
        /// </summary>
        [Required]

        [DataMember(Name="trucks")]
        public TrucksMetrics Trucks { get; set; }

        /// <summary>
        /// Gets or Sets Fleet
        /// </summary>
        [Required]

        [DataMember(Name="fleet")]
        public FleetMetrics Fleet { get; set; }

        /// <summary>
        /// Gets or Sets TruckOperators
        /// </summary>
        [Required]

        [DataMember(Name="truck_operators")]
        public TruckOperatorsMetrics TruckOperators { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LoadPlansMetrics {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Trucks: ").Append(Trucks).Append("\n");
            sb.Append("  Fleet: ").Append(Fleet).Append("\n");
            sb.Append("  TruckOperators: ").Append(TruckOperators).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LoadPlansMetrics)obj);
        }

        /// <summary>
        /// Returns true if LoadPlansMetrics instances are equal
        /// </summary>
        /// <param name="other">Instance of LoadPlansMetrics to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoadPlansMetrics other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Date == other.Date ||
                    Date != null &&
                    Date.Equals(other.Date)
                ) && 
                (
                    Trucks == other.Trucks ||
                    Trucks != null &&
                    Trucks.Equals(other.Trucks)
                ) && 
                (
                    Fleet == other.Fleet ||
                    Fleet != null &&
                    Fleet.Equals(other.Fleet)
                ) && 
                (
                    TruckOperators == other.TruckOperators ||
                    TruckOperators != null &&
                    TruckOperators.Equals(other.TruckOperators)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Date != null)
                    hashCode = hashCode * 59 + Date.GetHashCode();
                    if (Trucks != null)
                    hashCode = hashCode * 59 + Trucks.GetHashCode();
                    if (Fleet != null)
                    hashCode = hashCode * 59 + Fleet.GetHashCode();
                    if (TruckOperators != null)
                    hashCode = hashCode * 59 + TruckOperators.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LoadPlansMetrics left, LoadPlansMetrics right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LoadPlansMetrics left, LoadPlansMetrics right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
