/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SurveyResponse : IEquatable<SurveyResponse>
    { 
        /// <summary>
        /// Gets or Sets IdQuestion
        /// </summary>

        [DataMember(Name="idQuestion")]
        public int? IdQuestion { get; set; }

        /// <summary>
        /// Gets or Sets IdQualification
        /// </summary>

        [DataMember(Name="idQualification")]
        public int? IdQualification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SurveyResponse {\n");
            sb.Append("  IdQuestion: ").Append(IdQuestion).Append("\n");
            sb.Append("  IdQualification: ").Append(IdQualification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SurveyResponse)obj);
        }

        /// <summary>
        /// Returns true if SurveyResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of SurveyResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SurveyResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    IdQuestion == other.IdQuestion ||
                    IdQuestion != null &&
                    IdQuestion.Equals(other.IdQuestion)
                ) && 
                (
                    IdQualification == other.IdQualification ||
                    IdQualification != null &&
                    IdQualification.Equals(other.IdQualification)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (IdQuestion != null)
                    hashCode = hashCode * 59 + IdQuestion.GetHashCode();
                    if (IdQualification != null)
                    hashCode = hashCode * 59 + IdQualification.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SurveyResponse left, SurveyResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SurveyResponse left, SurveyResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
