/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Aqui se encuentran las respuestas de la encuesta por el operador
    /// </summary>
    [DataContract]
    public partial class SurveyResponses : IEquatable<SurveyResponses>
    { 
        /// <summary>
        /// Gets or Sets IdSurvey
        /// </summary>

        [DataMember(Name="idSurvey")]
        public int? IdSurvey { get; set; }

        /// <summary>
        /// Gets or Sets IdOperator
        /// </summary>

        [DataMember(Name="idOperator")]
        public int? IdOperator { get; set; }

        /// <summary>
        /// Gets or Sets _SurveyResponses
        /// </summary>

        [DataMember(Name="surveyResponses")]
        public List<SurveyResponse> _SurveyResponses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SurveyResponses {\n");
            sb.Append("  IdSurvey: ").Append(IdSurvey).Append("\n");
            sb.Append("  IdOperator: ").Append(IdOperator).Append("\n");
            sb.Append("  _SurveyResponses: ").Append(_SurveyResponses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SurveyResponses)obj);
        }

        /// <summary>
        /// Returns true if SurveyResponses instances are equal
        /// </summary>
        /// <param name="other">Instance of SurveyResponses to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SurveyResponses other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    IdSurvey == other.IdSurvey ||
                    IdSurvey != null &&
                    IdSurvey.Equals(other.IdSurvey)
                ) && 
                (
                    IdOperator == other.IdOperator ||
                    IdOperator != null &&
                    IdOperator.Equals(other.IdOperator)
                ) && 
                (
                    _SurveyResponses == other._SurveyResponses ||
                    _SurveyResponses != null &&
                    _SurveyResponses.SequenceEqual(other._SurveyResponses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (IdSurvey != null)
                    hashCode = hashCode * 59 + IdSurvey.GetHashCode();
                    if (IdOperator != null)
                    hashCode = hashCode * 59 + IdOperator.GetHashCode();
                    if (_SurveyResponses != null)
                    hashCode = hashCode * 59 + _SurveyResponses.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SurveyResponses left, SurveyResponses right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SurveyResponses left, SurveyResponses right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
