/*
 * Core.Api
 *
 * Documentación de api del TMS de Transportes Cuauhtémoc
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using TmsTcAPI.DAL.Models;
using IO.Swagger.Models;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Business;
using MarketType = IO.Swagger.Models.MarketType;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// Api encargada de las operaciones de tipos de mercado
    /// </summary>
    [ApiController]
    public class MarketTypesApiController : ControllerBase
    {
        private readonly TmsTcEntities context;

        public MarketTypesApiController(TmsTcEntities context)
        {
            this.context = context;
        }

        /// <summary>
        /// Obtiene los tipos de mercado
        /// </summary>
        /// <param name="active">Si se especifica filtra por estado habilitado o deshabilitado</param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad Request</response>
        [HttpGet]
        [Route("/market-types")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [AllowAnonymous]
        [ValidateModelState]
        [SwaggerOperation("GetMarketTypes")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<MarketType>), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request")]
        public virtual IActionResult GetMarketTypes([FromQuery]bool? active)
        {
            return new MarketTypesBusiness(context, User).GetMarketTypes(active);
        }

        /// <summary>
        /// Añade un tipo de mercado
        /// </summary>
        /// <param name="body">El tipo de mercado a añadir</param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        [HttpPost]
        [Route("/market-types")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("AddMarketType")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProblemDetails), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ProblemDetails), description: "Unauthorized")]
        public virtual IActionResult AddMarketType([FromBody][Required]MarketType body)
        {
            return new MarketTypesBusiness(context, User).AddMarketType(body);
        }

        /// <summary>
        /// Actualiza un tipo de mercado
        /// </summary>
        /// <param name="id">El id del tipo de mercado</param>
        /// <param name="body">El tipo de mercado modificado</param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        [HttpPut]
        [Route("/market-types/{id}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("UpdateMarketType")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProblemDetails), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ProblemDetails), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ProblemDetails), description: "Not Found")]
        public virtual IActionResult UpdateMarketType([FromRoute][Required]int id, [FromBody][Required]MarketType body)
        {
            return new MarketTypesBusiness(context, User).UpdateMarketType(id, body);
        }

        /// <summary>
        /// Deshabilita un tipo de mercado
        /// </summary>
        /// <param name="id">El id del tipo de mercado</param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        [HttpDelete]
        [Route("/market-types/{id}")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("DeleteMarketType")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProblemDetails), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(ProblemDetails), description: "Bad Request")]
        [SwaggerResponse(statusCode: 401, type: typeof(ProblemDetails), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(ProblemDetails), description: "Not Found")]
        public virtual IActionResult DeleteMarketType([FromRoute][Required]int id)
        {
            return new MarketTypesBusiness(context, User).DeleteMarketType(id);
        }
    }
}
