/*
 * Transportes Cuauhtémoc
 *
 * Transportes Cuauhtémoc (ASP.NET Core 3.1)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using CrmTc.DAL.Models;
using AuthenticationHandler.Controllers;
using IO.Swagger.Business;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class OfficesApiController : TmsControllerBase
    {
        protected CrmTcEntities CrmContext { get; private set; }

        public OfficesApiController(TmsTcAPI.DAL.Models.TmsTcEntities context, CrmTcEntities crmContext) : base(context)
        {
            CrmContext = crmContext;
        }
        /// <summary>
        /// Obtiene las oficinas en el sistema
        /// </summary>
        /// <response code="200">OK</response>
        /// <response code="401">Unauthorized</response>
        [HttpGet]
        [Route("/offices")]
        [Authorize(AuthenticationSchemes = BearerAuthenticationHandler.SchemeName)]
        [ValidateModelState]
        [SwaggerOperation("GetOffices")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Office>), description: "OK")]
        [SwaggerResponse(statusCode: 401, type: typeof(ProblemDetails), description: "Unauthorized")]
        public virtual IActionResult GetOffices()
        {
            return new OfficesBusiness(Context, CrmContext, User).GetOffices();
        }
    }
}
