/*
 * ITESM-LVCD
 *
 * Documentación de api del TMS de Transportes Cuauhtémoc
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using TmsTcAPI.DAL.Models;
using Microsoft.EntityFrameworkCore;
using TmsTcAPI.BLL.Business;
using TmsTcAPI.BLL.Interface;


namespace TmsTcAPI.Controllers
{
    public class CotizacionController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        DbContextOptions<TmsTcEntities> contextOptions;
        public CotizacionController(DbContextOptions<TmsTcEntities> options)
        {
            contextOptions = options;
        }
        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/ObtenerOrigenes")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerOrigenes(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }


        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/ObtenerDestinos")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerDestinos(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }

        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/Repartos")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerRepartos(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }

        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/ObtenerEstructuraCostos/Variables")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerEstructuraCostosVariables(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }

        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/ObtenerEstructuraCostos/Fijos")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerEstructuraCostosFijos(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }

        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/Regresos")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerRegresos(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }

        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/ObtenerPrecioFleteHistorico")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerPrecioFleteHistorico(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }

        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/ObtenerProbabilidadCarga")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerProbabilidadCarga(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }

        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Cotizacion" })]
        [HttpPost]
        [Route("Api/Cotizacion/GeneraTarifas")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult GeneraTarifas(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }

        ///// <summary>
        ///// Regresa la consulta de Paises
        ///// </summary>
        ///// <returns>string lista de paises</returns>
        //[SwaggerOperation(Tags = new[] { "Cotizacion" })]
        //[HttpPost]
        //[Route("Api/Cotizacion/ObtenerClientes")]
        //[ResponseType(typeof(JsonResult))]
        //public JsonResult ObtenerClientes(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        //{
        //    ICorreo correoBussines = new CorreoBusiness(contextOptions);
        //    var respuestaValor = correoBussines.EnviarCorreo("", "", "", "", "", "");

        //    return respuestaValor;
        //}




    }
}