/*
 * ITESM-LVCD
 *
 * Documentación de api del TMS de Transportes Cuauhtémoc
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using TmsTcAPI.DAL.Models;
using Microsoft.EntityFrameworkCore;
using TmsTcAPI.BLL.Business;
using TmsTcAPI.BLL.Interface;


namespace TmsTcAPI.Controllers
{
    public class OficinasController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        DbContextOptions<TmsTcEntities> contextOptions;
        public OficinasController(DbContextOptions<TmsTcEntities> options)
        {
            contextOptions = options;
        }
        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Oficinas" })]
        [HttpPost]
        [Route("Api/Oficinas/Rampas")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult AdministracionRampas(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }


        /// <summary>
        /// Regresa la consulta de Paises
        /// </summary>
        /// <returns>string lista de paises</returns>
        [SwaggerOperation(Tags = new[] { "Oficinas" })]
        [HttpPost]
        [Route("Api/Oficinas/Regresos")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult Regresos(string razonSocial, string nombreComercial, int Holdings, float nombreHolding, float porcentaje)
        {
            return new Models.JsonResult { Data = null, Mensaje = "" };
        }


    }
}