/*
 * ITESM-LVCD
 *
 * Documentación de api del TMS de Transportes Cuauhtémoc
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using TmsTcAPI.DAL.Models;
using Microsoft.EntityFrameworkCore;
using TmsTcAPI.BLL.Business;
using TmsTcAPI.BLL.Interface;

namespace TmsTcAPI.Controllers
{
    public class RutasController //: IRutas
    {
        DbContextOptions<TmsTcEntities> contextOptions;
        public RutasController(DbContextOptions<TmsTcEntities> options)
        {
            contextOptions = options;
        }
        /// <summary>
        /// Regresa la ruta generada por GlobalMap entre un punto de Origen y uno de Destino
        /// </summary>
        /// <returns>string valores de una ruta</returns>
        [SwaggerOperation(Tags = new[] { "Rutas" })]
        [HttpGet]
        [Route("Api/Rutas/GestorRutas")]
        [SwaggerResponse(statusCode: 200, type: typeof(Models.JsonResult), description: "OK")]
        public Models.JsonResult ObtenerInfoRuta( 
             string OrigenLatitude
            ,string OrigenLongitude
            ,string DestinoLatitude
            ,string DestinoLongitude
            ,string TipoVehiculo
            //,string PesoVehiculo
            //,string LargoVehiculo
            //,string AnchoVehiculo
            //,string AlturaVehiculo
            //,string EvitarCasetas
            //,string EvitarFerrys
            //,string OptimizarParadas
            //,string OptimizarNOM
            //,string RutaCamion
            //,string Velocidad
            )
        {
            IRutas rutas = new RutasBusiness(contextOptions);

            Models.JsonResult jRes = new Models.JsonResult();

            jRes.Data = rutas.ObtenerInfoRuta(
                OrigenLatitude
                , OrigenLongitude
                , DestinoLatitude
                , DestinoLongitude
                , TipoVehiculo
                //, PesoVehiculo
                //, LargoVehiculo
                //, AnchoVehiculo
                //, AlturaVehiculo
                //, EvitarCasetas
                //, EvitarFerrys
                //, OptimizarParadas
                //, OptimizarNOM
                //, RutaCamion
                //, Velocidad
                );

            return jRes;

        }

    }

}